config/routes.rb
Rails.application.routes.draw do
  match "admin", to: 'static_pages#admin', via: :get, as: :admin
  match "dktest", to: 'static_pages#dktest', via: :get
  root 'static_pages#index'

  resources :papers do
    member do
      get 'serve'
    end
  end

  resources :travels, except: :show
  resources :updates
  resources :awards
  resources :authors, only: :index
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate, :except => [:index]

  def index
    @updateAssetMap = {
      Update::Type::PAPER.to_s => ActionController::Base.helpers.asset_url("paper_update.png"),
      Update::Type::AWARD.to_s => ActionController::Base.helpers.asset_url("award_update.png"),
      Update::Type::TRAVEL.to_s => ActionController::Base.helpers.asset_url("travel_update.png"),
      Update::Type::PRESS.to_s => ActionController::Base.helpers.asset_url("press_update.png"),
      Update::Type::PRESENTATION.to_s => ActionController::Base.helpers.asset_url("prez_update.png"),
      Update::Type::MISC.to_s => ActionController::Base.helpers.asset_url("misc_update.png")
    }

    @paperAssetMap = {
      "noThumb" => ActionController::Base.helpers.asset_url("no-image.png"),
      "pdfDL" => ActionController::Base.helpers.asset_url("pdf.png"),
      "slidesDL" => ActionController::Base.helpers.asset_url("slides.png"),
      "prezDL" => ActionController::Base.helpers.asset_url("presentation.png"),
      "videoDL" => ActionController::Base.helpers.asset_url("video.png"),
      "tweetsDL" => ActionController::Base.helpers.asset_url("tw_black.png")
    }

    @courses = [{
      courseCode: "GT CS4001",
      courseName: "Computing, Society & Professionalism",
      semester: "Spring 2018",
      link: "http://cs4001.sauvik.me"
    }, {
      courseCode: "GT CS4001",
      courseName: "Computing, Society & Professionalism",
      semester: "Fall 2018",
      link: "http://cs4001.sauvik.me"
    }, {
      courseCode: "GT CS4/8803 UPS",
      courseName: "Usable Privacy & Security",
      semester: "Spring 2019",
      link: "http://cs8803.sauvik.me"
    }, { 
      courseCode: "GT CS4873",
      courseName: "Computing, Society & Professionalism",
      semester: "Fall 2020",
      link: "http://cs4873c.sauvik.me"
    }, {
      courseCode: "GT CS4/8803 UPS",
      courseName: "Computing, Society & Professionalism",
      semester: "Spring 2022",
      link: "http://cs8803.sauvik.me"
    },
    { 
      courseCode: "CMU 05-120 A1",
      courseName: "Intro to HCI",
      semester: "Fall 2022",
      link: "https://canvas.cmu.edu/courses/31234"
    },
    {
      courseCode: "CMU 05/17-200",
      courseName: "Ethics and Policy Issues in Computing",
      semester: "Spring 2023",
      link: "https://canvas.cmu.edu/courses/33066/assignments/syllabus"
    },
    {
      courseCode: "CMU 05-4/630",
      courseName: "Programming Usable Interfaces",
      semester: "Spring 2024",
      link: "https://canvas.cmu.edu/courses/38964/assignments/syllabus"
    },
    {
      courseCode: "CMU 05-4/899 D",
      courseName: "Building Technologies for the Resistance (BTR)",
      semester: "Fall 2024",
      link: "https://bit.ly/btr-syllabus"
    },
    {
      courseCode: "CMU 05-3/891 A",
      courseName: "Designing Human-Centered Software (DHCS)",
      semester: "Spring 2025",
      link: "https://bit.ly/s25-dhcs-a"
    },
    {
      courseCode: "CMU 05-3/891 D",
      courseName: "Designing Human-Centered Software (DHCS)",
      semester: "Fall 2025",
      link: "https://bit.ly/f25-dhcs-d"
    },
    {
      courseCode: "CMU 05-4/899 D",
      courseName: "Building Technologies for the Resistance (BTR)",
      semester: "Spring 2026",
      link: "https://bit.ly/s26-btr"
    },
    ].reverse

    all_students = [
      {
        name: "Youngwook Do",
        link: "http://www.youngwookdo.me/",
        image: ActionController::Base.helpers.asset_url("ywd.png"),
        info: "Phyiscally-intuitive security",
        alum: true,
        now: "now: JP Morgan Chase",
        years: "2018-2023"
      },
      {
        name: "Yuxi Wu",
        link: "https://yuxi-wu.github.io/",
        image: ActionController::Base.helpers.asset_url("yw.jpg"),
        info: "Privacy collectve action",
        alum: true,
        now: "now: Postdoc at Northeastern",
        years: "2019-2024"
      },
      {
        name: "Jacob Logas",
        link: "https://logas.me/",
        image: ActionController::Base.helpers.asset_url("pjl.jpg"),
        info: "Subversive AI",
        alum: true,
        now: "now: Asst. Prof (Franklin & Marshall)",
        years: "2019-2025"
      },
      {
        name: "Hao-Ping (Hank) Lee",
        link: "https://hankhplee.com/",
        image: ActionController::Base.helpers.asset_url("hhpl.jpg"),
        info: "AI Privacy",
        alum: false,
        now: "CMU Ph.D.",
        years: "2021-present"
      },
      {
        name: "Isadora Krsek",
        link: "https://www.isadorakrsek.com/",
        image: ActionController::Base.helpers.asset_url("ik.jpg"),
        info: "NLP for privacy / security",
        alum: false,
        now: "CMU Ph.D.",
        years: "2022-present"
      },
      {
        name: "Kyzyl Monteiro",
        link: "https://www.kyzyl.me/",
        image: ActionController::Base.helpers.asset_url("km.jpg"),
        info: "Intelligent agents for security",
        alum: false,
        now: "CMU Ph.D.",
        years: "2023-present"
      },
      {
        name: "William Agnew",
        link: "https://sites.google.com/cs.washington.edu/william-agnew/home",
        image: ActionController::Base.helpers.asset_url("wa.png"),
        info: "Community-centered AI",
        alum: false,
        now: "CMU Postdoc",
        years: "2023-present"
      },
      {
        name: "Yuxuan Li",
        link: "https://yuxuanli.com/",
        image: ActionController::Base.helpers.asset_url("yl.jpg"),
        info: "Social agent simulation & policy",
        alum: false,
        now: "CMU Ph.D.",
        years: "2024-present"
      }
    ]

    # Separate current students and alums
    @currentStudents = all_students.select { |student| !student[:alum] }
    @alums = all_students.select { |student| student[:alum] }
  end

  def dktest
    @params = params
    p params
  end

  def admin
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |user, password|
        retval = user == ENV['PERSONAL_UN'] && password == ENV['PERSONAL_PASS']
        session[:authenticated] = true if retval
        retval
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.haml
.row
  .col-md-12
    = react_component('AdminContainer', papersURL: papers_url(format: :json), updatesURL: updates_url(format: :json), awardsURL: awards_url(format: :json), travelsURL: travels_url(format: :json))

app/views/static_pages/dktest.html.haml
.row
  .col-md-12
    %p=@params

app/views/static_pages/index.html.haml
-# = react_component('TravelContainer', url: travels_url(format: :json), pollInterval: 10000)
.row
  .col-md-6
    %p{class: "about-header"}
      About
    .bio
      %p
        I am an Associate Professor (without indefinite tenure) at
        =link_to "Carnegie Mellon University's", "https://www.cmu.edu"
        =link_to "Human-Computer Interaction Institute.", "https://www.hcii.cmu.edu"
        I am also co-founder and Chief Technology Officer of
        =link_to "FuguUX,", "https://www.fuguux.com"
        an early-stage start-up dedicated to improving web usability.
      %p
        At CMU, I direct the
        =link_to "SPUD (Security, Privacy, Usability and Design) Lab.", "https://cs.cmu.edu/~spudlab"
        Our work, at the intersection of HCI, AI and cybersecurity, is oriented around answering the question:
        %strong How can we design systems that empower people with improved agency over their personal data and experiences online?
        Some past and present research directions include:
        %ul
          %li
            %b
              Practitioner Support for AI Privacy:
            =link_to "Privy: AI Privacy Risk Assessment Tool (CHI)", "https://www.sauvik.me/papers/69/serve", class: "project-highlight", target: "_blank"
            =link_to "AI Privacy Taxonomy (CHI Best Paper)", "https://sauvikdas.com/papers/51/serve", class: "project-highlight", target: "_blank"
            =link_to "Barriers to AI Privacy Work (USENIX SEC Distinguished Paper)", "https://sauvikdas.com/papers/47/serve", class: "project-highlight", target: "_blank"
            =link_to "Designing for AI Privacy (CSCW Honorable Mention)", "https://sauvikdas.com/papers/31/serve", class: "project-highlight", target: "_blank"
            =link_to "Keynote talk — Privacy@Michigan 2025", "https://safecomputing.umich.edu/events/privacy/privacy-2025/dr-sauvik-das", class: "project-highlight", target: "_blank"
            =link_to "USENIX PEPR talk", "https://www.youtube.com/watch?v=69GqgR_arOo", class: "project-highlight", target: "_blank"
          %li
            %b
              Human-AI Teaming for Security & Privacy:
            =link_to "Image Ally (SOUPS)", "https://sauvikdas.com/papers/43/serve", class: "project-highlight", target: "_blank"
            =link_to "Self-Disclosure Detection Model (ACL)", "https://sauvikdas.com/papers/55/serve", class: "project-highlight", target: "_blank"
            =link_to "Helping People Make Informed Disclosure Decisions (CSCW)", "https://sauvikdas.com/papers/58/serve", class: "project-highlight", target: "_blank"
            =link_to "Quantifying Privacy Risk in Self-Disclosures using AI (NeurIPS)", "https://www.sauvik.me/papers/67/serve", class: "project-highlight", target: "_blank" 
            =link_to "Presenting AI Estimated Privacy Risks to Users (CHI)", "https://www.sauvik.me/papers/70/serve", class: "project-highlight", target: "_blank"
          %li
            %b
              Human-centered Adversarial Machine Learning:
            =link_to "Subversive AI (Resistance AI Workshop)", "https://sauvikdas.com/papers/27/serve", class: "project-highlight", target: "_blank"
            =link_to "Measuring Human-acceptability of Adversarial Perturbations (CSCW)", "https://sauvikdas.com/papers/49/serve", class: "project-highlight", target: "_blank"
            =link_to "Data Defenses againt Large Language Models (pre-print)", "https://arxiv.org/abs/2410.13138", class: "project-highlight", target: "_blank"
          %li
            %b
              Ethical Design for and with Language Agent Simulations:
            =link_to "Language Agent Simulations Reveal Implicit Bias in LLMs (pre-print)", "https://arxiv.org/html/2501.17420v1", class: "project-highlight", target: "_blank"
          %li
            %b
              Privacy Collective Action & Governance:
            =link_to "Orchestrating distributed collectives for privacy (CHI)", "https://sauvikdas.com/papers/39/serve", class: "project-highlight", target: "_blank"
            =link_to "Taxonomy of Lived Privacy Harms (FAccT)", "https://sauvikdas.com/papers/42/serve", class: "project-highlight", target: "_blank"
            =link_to "Design Fictions for Privacy Harm Reporting (CSCW)", "https://sauvikdas.com/papers/56/serve", class: "project-highlight", target: "_blank"
            =link_to "Privacy for the People Vision (IEEE S&P Mag)", "https://sauvikdas.com/papers/32/serve", class: "project-highlight", target: "_blank"
          %li
            %b
              Physically-intuitive Privacy and Security (PIPS):
            =link_to "Smart Webcam Cover (IMWUT)", "https://sauvikdas.com/papers/35/serve", class: "project-highlight", target: "_blank"
            =link_to "Powering for Privacy (USENIX SEC)", "https://sauvikdas.com/papers/46/serve", class: "project-highlight", target: "_blank"
            =link_to "On-demand RFID (USEC)", "https://sauvikdas.com/papers/62/serve", class: "project-highlight", target: "_blank"
          %li
            %b
              Social cybersecurity:
            =link_to "Social Proof Increases Security Acceptance (CCS; NSA Best Scientific Cybersecurity Paper Honorable Mention)", "https://sauvikdas.com/papers/9/serve", class: "project-highlight", target: "_blank" 
            =link_to "SoK: Social Cybersecurity (Oakland)", "https://sauvikdas.com/papers/36/serve", class: "project-highlight", target: "_blank"
            =link_to "How Groups Make Security Decisions (CHI Honorable Mention)", "https://sauvikdas.com/papers/23/serve", class: "project-highlight", target: "_blank"
            =link_to "A Design Space for Group Cybersecurity Controls (USENIX SEC)", "https://sauvikdas.com/papers/34/serve", class: "project-highlight", target: "_blank"
            =link_to "USENIX Enigma Talk", "https://www.youtube.com/watch?v=jcIlE4dGdWY", class: "project-highlight", target: "_blank"
      %p
        A few of my papers have been recognized with awards:
        a best paper at UbiComp (2013) and CHI (2024),
        a distinguished paper at SOUPS (2020) and USENIX Security (2024),
        four best paper honorable mentions at CHI (2016, 2017, 2020, 2024),
        a best paper honorable mention at CSCW (2021),
        and an honorable mention for the NSA's Best Scientific Cybersecurity Paper (2014).
        My lab's work has been generously supported by the NSF, Facebook, Georgia Tech, and CMU.
        My work has also been covered by the popular press, including features on The Atlantic, The Financial Times and Dark Reading.
      %h4
        Prospective Ph.D. Students
      %p
        I am always on the lookout for talented Ph.D. students.
        If you are interested in working with me, I encourage you to apply to the
        = link_to "HCII Ph.D.", "https://www.hcii.cmu.edu/academics/phd-hci"
        at Carnegie Mellon and mention my name in your application.
        I'm afraid that I am unlikely to respond to cold e-mails; I just have too many
        other things to do in my limited workday.
        A few years ago, I made a
        = link_to "YouTube video", "https://www.youtube.com/watch?v=JqD2arlzXVE"
        on improving your odds at landing a position in a C.S. Ph.D. program.
      -# %p
        -# I write two (infrequently updated) blogs:
        -# =link_to "an academic blog,", "https://medium.com/@scyrus89"
        -# and
        -# =link_to "a privacy and security blog", "https://consult.sauvik.me"
        -# and a
        -# =link_to "vlog", "https://www.youtube.com/channel/UCn4ZcBS7p7N4KwVmJwy3bzQ?view_as=subscriber"
        -# covering topics on academia and research in HCI and cybersecurity.
    %hr
    = react_component('StudentsContainer', currentStudents: @currentStudents, alums: @alums)
  .col-md-6
    = react_component('TabContainer', 
        papersUrl: papers_url(format: :json), 
        paperAssets: @paperAssetMap, 
        paperPollInterval: 10000,
        awardsUrl: awards_url(format: :json),
        courses: @courses,
        currentStudents: @currentStudents,
        alums: @alums)